services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: "database"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb

  importer:
    build: .
    command: python -u data_import.py
    environment:
      REDDIT_CLIENT_ID: "${REDDIT_CLIENT_ID}"
      REDDIT_CLIENT_SECRET: "${REDDIT_CLIENT_SECRET}"
      REDDIT_USER_AGEND: "${REDDIT_USER_AGEND}"
    volumes:
      - .:/code

volumes:
  mongodb_data:
